---

# Install GovReady.
# Depends on SCAP Security Guide already having been installed.
# Consider using the govready installer instead of cloning...

- name: Clone GovReady repository
  git:
    repo: "{{ govready_repo }}"
    dest: "{{ govready_repo_local_destination }}"
  become: true

- name: Create link to govready executable in /usr/local/bin
  file:
    src: "{{ govready_executable_src }}"
    dest: "{{ govready_executable_link }}"
    state: link
  become: true

- name: Create myfisma/ subdirectory
  file:
    path: "{{ govready_myfisma_directory }}"
    state: directory

- name: Initialize GovReady
  command: chdir="{{ govready_myfisma_directory }}" govready init

- name: Rename default GovReadyfile to GovReadyfile.init
  command: mv "{{ govready_configuration_file }}" "{{ govready_configuration_file }}".init

- name: Install GovReadyfile for 192.168.56.102 centos7 machine
  copy:
    src: GovReadyfile
    dest: "{{ govready_configuration_file }}"

- name: Remove myfisma/scap directory
  file:
    path: "{{ govready_scap_myfisma_directory }}"
    state: absent

- name: Create link to SCAP content
  file:
    src: "{{ govready_scap_content_directory }}"
    dest: "{{ govready_scap_myfisma_directory }}"
    state: link
    force: yes
