# vi: set ft=ruby

require 'rbconfig'
require 'yaml'

VAGRANTFILE_API_VERSION = '2'
PROJECT_NAME = '/' + File.basename(Dir.getwd)

# Set your default base box here.
DEFAULT_BASE_BOX = 'centos/7'
# DEFAULT_BASE_BOX = 'https://github.com/CommanderK5/packer-centos-template/releases/download/0.7.2/vagrant-centos-7.2.box"

hosts = YAML.load_file('vagrant_hosts.yml')
  
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # Create the dashboard and server instances.
  hosts.each do |host|
    config.vm.define host['name'] do |node|
      node.vm.box = host['box'] ||= DEFAULT_BASE_BOX
      node.vm.network "private_network", ip: host['ip']
      # centos/7 forces one-time rsync on /vagrant, so disable this.
      node.vm.synced_folder ".", "/vagrant", disabled: true
      # Create a share folder used for scans output.
      node.vm.synced_folder host['name'], "/home/vagrant/v-share", create: true
      node.vm.provider "virtualbox" do |vb|
        vb.name = host['name']
        vb.customize ['modifyvm', :id, '--groups', PROJECT_NAME]
      end
    end
  end
  # Provision the instances.
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "test.yml"
  end
end
