# vi: set ft=ruby

require 'rbconfig'
require 'yaml'

VAGRANTFILE_API_VERSION = '2'
PROJECT_NAME = '/' + File.basename(Dir.getwd)

# Set your default base box here
DEFAULT_BASE_BOX = 'geerlingguy/centos7'

hosts = YAML.load_file('vagrant_hosts.yml')
  
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  hosts.each do |host|
    config.vm.define host['name'] do |node|
      node.vm.box = host['box'] ||= DEFAULT_BASE_BOX
      node.vm.box_check_update = true
      node.ssh.insert_key = false
      node.vm.network :private_network, ip: host['ip']
      node.vm.synced_folder ".", "/vagrant", group: "vagrant", owner: "vagrant", create: true
      node.vm.provider "virtualbox" do |vb|
        vb.name = host['name']
        vb.customize ['modifyvm', :id, '--groups', PROJECT_NAME]
      end
    end
  end
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "test.yml"
  end
end
